# Generated by Django 4.1.5 on 2023-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_remove_document_author_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
